### ISSUE TITLE
FBX format compilation error

### ISSUE THREAD

**Issue by dairectx** [ncannasse/heaps#126]
There is an odd fbx file, when I compile it, Heaps report an error:

    C:\HaxeToolkit\haxe\lib\heaps/git/hxd/fmt/fbx/BaseLibrary.hx:270: characters 3-8 : Missing  Model child
    C:\HaxeToolkit\haxe\lib\heaps/git/hxd/fmt/fbx/BaseLibrary.hx:507: characters 20-45 : Called from
    C:\HaxeToolkit\haxe\lib\heaps/git/hxd/fmt/fbx/BaseLibrary.hx:1013: characters 3-47 : Called from
    C:\HaxeToolkit\haxe\lib\heaps/git/hxd/fmt/fbx/HMDOut.hx:645: characters 2-13 : Called from
    C:\HaxeToolkit\haxe\lib\heaps/git/hxd/res/FileTree.hx:144: characters 14-111 : Called from
    C:\HaxeToolkit\haxe\lib\heaps/git/hxd/res/FileTree.hx:86: characters 8-50 : Called from
    C:\HaxeToolkit\haxe\lib\heaps/git/hxd/res/FileTree.hx:64: characters 18-30 : Called from
    C:\HaxeToolkit\haxe\lib\heaps/git/hxd/fs/EmbedFileSystem.hx:263: characters 13-29 : Called from
    C:\HaxeToolkit\haxe\lib\heaps/git/hxd/Res.hx:15: characters 51-95 : Called from

I try to figure out what happened, but no lucky.
Maybe it's a bug? The fbx file is valid. It can import to Unity and play animation with no problem.

(The sample fbx file has sended to author's email)

**Comment by ncannasse** [comment]
I've made a partial fix for it. It now loads but does not display properly. That's because Heaps expect one single object to be attached to a single Skin. In case it does find several objects attached to the skin, he tries to merge them into one single object (hxd.fmt.fbx.BaseLibrary.mergeModels)

However, it seems the merge fails in this case, I'll keep it open until I fix it.

In the meanwhile, you can manually merge your objects in your 3D editor, using one single object with multiple materials

**Comment by matrix3d** [comment]
try this app http://matrix3d.github.io/assets/native3d/modelviewer/

**Comment by ncannasse** [comment]
Note: several FBX skin support improvements were made in the past year, the limit of one skin per object is still relevant.
